### PR TITLE
1DB1A6C6.pnach and 7884CDB0.pnach

### PR DESCRIPTION
**Pull request by Martyste**
Adding No-Interlacing patches for the following games:
Asterix & Obelix XXL (PAL M-5, SLES-51838)
Asterix & Obelix Kick Buttix (NTSC-U, SLUS-20866)

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
Could you please use the new naming format? so SERIAL_CRC.pnach

also ideally you should use description rather than comment

**Comment by refractionpcsx2** [comment]
You need to delete the old patch

**Comment by Martyste** [comment]
Everything should be fixed and set! I took the opportunity to update the syntax of both files for the new system, as well as replicate a patch only one game had, into the other. Sorry for all this mess, it's my first time using Github and it's been slow, reading a tutorial whenever i needed to make any action. Should be fine now!

**Comment by refractionpcsx2** [comment]
You need to delete the old patch.

**Comment by Martyste** [comment]
This Branch has a few messy un-removable things like merge pulls, I'm closing it in favor of a new clean one. Sorry again for the troubles!

**Pull request closed without merging**
