### PR TITLE
Boku no Natsuyasumi 2 - High Resolution Fix

### PR DESCRIPTION
**Pull request by MrWrightyLC**
this patch was made to be used only for the english translation, the japanese version has a different crc and is not intended to be used with that one.

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
may i ask what it fixes ?

**Comment by MrWrightyLC** [comment]
> may i ask what it fixes ?

fixes broken text when using a superior resolution than native

without patch
Boku no Natsuyasumi 2 - Umi no Bouken-hen_SCPS-15026_20231213131049
Boku no Natsuyasumi 2 - Umi no Bouken-hen_SCPS-15026_20231213131308

with patch
Boku no Natsuyasumi 2 - Umi no Bouken-hen_SCPS-15026_20231213131106
Boku no Natsuyasumi 2 - Umi no Bouken-hen_SCPS-15026_20231213131320

**Comment by MrWrightyLC** [comment]
these screenshots were taken using 3x Native (1080p)

**Comment by Mrlinkwii** [comment]
i feel like this can be fixed with up-scaling fixes rather than a patch

**Comment by MrWrightyLC** [comment]
> i feel like this can be fixed with up-scaling fixes rather than a patch can i have a gs dump

sure
https://drive.google.com/file/d/100XBy09aY_5dM-10FR1KjRCSoel3wV0f/view?usp=sharing

**Comment by Mrlinkwii** [comment]
i have check it ans it seems 
image fixes it 
image

**Comment by MrWrightyLC** [comment]
Yes! it works, I will close this pr, thanks for finding this fix, it is better than using a patch.

**Comment by Mrlinkwii** [comment]
@MrWrightyLC  ill try to get that added to the upscaling fixes

**Pull request closed without merging**
