### PR TITLE
ICO - formating, additions and improvements

### PR DESCRIPTION
**Pull request by pgert**

### CODE REVIEW

**Comment by pgert** [comment]
Well crap. 20:9 & 21:9 removed.

**Comment by pgert** [comment]
> For the debug menu patch, including info about how to change the framerate is redundant thanks to the 60 fps patch. The 60 fps patch already forces the debug framestep value to 1 (and 2 during cutscenes) so even if the user tried to change it, there would be no effect.

I have made it into a non-displaying comment instaed.

> For the 21:9/20:9 patch, I tried it out and didn’t get a single crash. Is it reproducible?

@PeterDelta ?

**Comment by pgert** [comment]
There shouldn't be any problems with 16:10 & 15:10.
The hacks for 20:9 & 21:9 are a bit different than for 16:10 & 15:10,
 and thats probably why there are imperfections.

**Comment by crashGG** [comment]
Hi, bro, could you port these patches to SCPS-55001_29C28734 (Asian) and SCCS-4005_BF3A46DA (China) of Ico? Thank you very much!

**Comment by pgert** [comment]
> Hi, bro, could you port these patches to SCPS-55001_29C28734 (Asian) and SCCS-4005_BF3A46DA (China) of Ico? Thank you very much!

No, I can't.
Try making a request at the forum:
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

**Review by F0bes — APPROVED** [review]

**Pull request merged**
