### PR TITLE
Silent Hill: Shattered Memories Patches

### PR DESCRIPTION
**Pull request by IWILLCRAFT-M0d**
Silent Hill - Shattered Memories: Splitted the no noise hack from the Widescreen hack, "author=" parameter added, and added support for the no noise hack in European release

### CODE REVIEW

**Comment by pgert** [comment]
If you're up for it, then add these:

------------

Silent Hill: Shattered Memories * NTSC-U * SLUS-21899 * 61A7E622

[Widescreen 16:10]
gsaspectratio=Stretch
author=converted by pgert
comment=Combine with 'Widescreen 16:9'.
patch=1,EE,002c4524,word,3c013FBD
patch=1,EE,002c4528,word,3421A12F

[Widescreen 15:10]
gsaspectratio=Stretch
author=converted by pgert
comment=Combine with 'Widescreen 16:9'.
patch=1,EE,002c4524,word,3c013FCA
patch=1,EE,002c4528,word,34214588

------------

Silent Hill: Shattered Memories * PAL-M5 * SLES-55569 * 492CB73E

[Widescreen 16:10]
gsaspectratio=Stretch
author=converted by pgert
comment=Combine with 'Widescreen 16:9'.
patch=1,EE,002c470c,word,3c013FBD
patch=1,EE,002c4710,word,3421A12F

[Widescreen 15:10]
gsaspectratio=Stretch
author=converted by pgert
comment=Combine with 'Widescreen 16:9'.
patch=1,EE,002c470c,word,3c013FCA
patch=1,EE,002c4710,word,34214588

------------

Silent Hill: Shattered Memories * NTSC-J * SLPM-55231 * F66FAFB2

[Widescreen 16:10]
gsaspectratio=Stretch
author=converted by pgert
comment=Combine with 'Widescreen 16:9'.
patch=1,EE,002c4a0c,word,3c013FBD
patch=1,EE,002c4a10,word,3421A12F

[Widescreen 15:10]
gsaspectratio=Stretch
author=converted by pgert
comment=Combine with 'Widescreen 16:9'.
patch=1,EE,002c4a0c,word,3c013FCA
patch=1,EE,002c4a10,word,34214588

------------

**Comment by F0bes** [comment]
Are you interested in adding the above patches?

**Comment by IWILLCRAFT-M0d** [comment]
> Are you interested in adding the above patches?
Yeah but I can't test them

**Comment by pgert** [comment]
> Yeah but I can't test them

Configure Windowed-mode to 1600:1000 for 16:10, or 1500:1000 for 15:10,
 then run the game in Windowed-mode.

**Comment by Mrlinkwii** [comment]
whats ths status of the pr?

**Comment by IWILLCRAFT-M0d** [comment]
> whats ths status of the pr?

I guess it was reviewed, but expecting to add the codes pgert shared, but as previously commented they seems to not be correct so I didn't added, however this has been taking so long that I decided to add a black border removal patch for Shattered Memories I found (like the one that Origins has) and added no noise filter for USA and EUR Origins

**Comment by F0bes** [comment]
My apologies, I don't check this repo often.

**Pull request merged**
