### PR TITLE
Add many 60 FPS patches

### PR DESCRIPTION
**Pull request by icup321**
Adds many patches from various sources, mainly asasega's 60 FPS patches and NTSC versions of PeterDelta's patches.

### CODE REVIEW

**Comment by Mrlinkwii** [comment]
are any of these tested ?

**Comment by icup321** [comment]
> are any of these tested ?

The vast majority of these have been tested to work. Most of these games share the same engines so I've at least had the codes tested on each game engine. I also had to modify some of them to get them to work properly as well.

**Comment by Mrlinkwii** [comment]
@icup321  can you rebase this pr for me

**Comment by icup321** [comment]
Should be rebased now, can't squash all commits but shouldn't be a big deal

**Pull request merged**
