### PR TITLE
Added Star Wars Episode III - Revenge of the Sith NTSC 60 FPS patch.

### PR DESCRIPTION
**Pull request by J-McFc**
I've played through the whole game with the patch and had no issues, although the main menu FMV is double speed but not game breaking of course.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
I would rather the FMV issue was fixed, before we merge it, maybe the patch could be made conditional on something else to switch when needed.

**Comment by fox140cv** [comment]
This solves it, it is from the PAL version that also works here:

patch=1,EE,E0010002,extended,001B4344
patch=1,EE,201AF538,extended,00000001

I was going to add it along with other patches I'm testing, so we already have this one, try it and add it.

**Comment by J-McFc** [comment]
Yep this works perfect for me, FMV plays at normal speed. I'll update it.

**Comment by refractionpcsx2** [comment]
Awesome, thanks folks, good teamwork :)

**Pull request merged**
