### PR TITLE
Burnout Revenge/Dominator Patches Update

### PR DESCRIPTION
**Pull request by MrWrightyLC**
### Burnout Revenge (U)(SLUS-21242)
**[Progressive Scan] always ask for 480p**
**[MPH to KPH] Miles per hour to Kilometres per hour speedometer**

### Burnout Dominator (U)(SLUS-21596)
**[Widescreen 16:9 and 21:9] new entire patch by SuperType1 (https://www.youtube.com/watch?v=fXY97XEIQQ8)**
**[60 FPS Menus and Crashes] 60fps menus and crash cam**

### CODE REVIEW

**Comment by MrWrightyLC** [comment]
The author's github profile shows both Nahelam and Nehalem, it is confusing...

**Comment by ElTioRata** [comment]
lol we almost made the same PR (i skipped dominator because it wasn't my priority)

author's correct alias is **Nahelam** i just misspelled it on the pr i made a few months back

**Comment by ElTioRata** [comment]
lol we almost made the same PR (i skipped dominator because it wasn't my priority), author's correct alias may be both, but just in case i changed it to nehalem

**Comment by MrWrightyLC** [comment]
> lol we almost made the same PR (i skipped dominator because it wasn't my priority), author's correct alias may be both, but just in case i changed it to nehalem, i will close my pr in favor of yours

no problem, I was very surprised that someone also made a similar pr. xD

**Review by JordanTheToaster — APPROVED** [review]

**Pull request merged**
