### PR TITLE
WS: Disable MGS 3 Sub WS

### LINKED ISSUE #417: MGS3 Snake Eater: Water refraction is still 4:3 when using Widescreen patch
This is for the base NTSC Snake Eater, Subsistence's widescreen does not have the same issue.

Using the widescreen patch when in areas that have water (ie the Swamp immediately after meeting EVA).

Refraction is still limited to 4:3

Example:
ogFym72

### PR DESCRIPTION
**Pull request by JordanTheToaster**
Fixes #417

### CODE REVIEW

**Comment by pgert** [comment]
"Subsistence's widescreen does not have the same issue".
Still, you disabled the hack for it as well.
Any comment?

**Comment by lightningterror** [comment]
It was reported that Subsistence experienced similar issues.

**Comment by ShizCalev** [comment]
> It was reported that Subsistence experienced similar issues.

>This is for the base NTSC Snake Eater, **Subsistence's widescreen does not have the same issue.**

Subsistence does NOT have the same issue.

**Comment by lightningterror** [comment]
Yes it was reported on discord.

**Pull request merged**
