### PR TITLE
Fix Ace Combat 04: Shattered Skies widescreen

### PR DESCRIPTION
**Pull request by FuxorLuck**
The Widescreen Hack for Ace Combat 04: Shattered Skies (and possibly all the other versions) doesn't work

CRC - A32F7CD0

Here is the current Hack

//widescreen fix
patch=1,EE,0040DACC,word,441CF7AE

The Game looks the same with or without the hack
image

Here is my new Hack

//WideScreen
patch=1,EE,0010c9f4,word,3c014455 //3c014420

and this is how the game looks
image

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
why are you deleting a ton of patches? :/

**Comment by FuxorLuck** [comment]
> why are you deleting a ton of patches? :/

No idea why it uploaded some old patches.

I only want to change A32F7CD0.pnach

**Comment by refractionpcsx2** [comment]
Anything happening with this?

**Comment by refractionpcsx2** [comment]
Assuming this is abandoned, you can open a new PR if you come back to it.

**Comment by pgert** [comment]
"patch=1,EE,0040DACC,word,441CF7AE" allegedly require screen ratio 16:9 to be enabled in options to work.
Assumably the build-in widescreen isn't true 16:9, so the patch corrects that.

https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=620200#pid620200

**Pull request closed without merging**
