### PR TITLE
Update SLUS-21242_D224D348.pnach

### PR DESCRIPTION
**Pull request by Guspr181**
I added the fixes made by SuperType1 from his video [https://www.youtube.com/watch?v=fXY97XEIQQ8](url) and update them to the new patches format to make them more comfortable to use.

### CODE REVIEW

**Comment by refractionpcsx2** [comment]
One thing I'm confused about, the addresses in the patch lines imply `extended` mode patches, but you've used `word`

**Comment by Guspr181** [comment]
> One thing I'm confused about, the addresses in the patch lines imply `extended` mode patches, but you've used `word`

I didn't make the patch so I don't know why the original creator make it in that way, but anyways I changed it to `extended`

**Comment by refractionpcsx2** [comment]
Thanks, can you confirm the patch still works post changes? If so then I can merge it :)

**Comment by Guspr181** [comment]
> Thanks, can you confirm the patch still works post changes? If so then I can merge it :)

Yes, it still works, I already test it and it worked.

**Pull request merged**
